export const categories = [
    { name: 'All Categories', value: '' },
    { name: 'Amazon', value: 'amazon' },
    { name: 'Apple Air pods', value: 'apple-air-pods' },
    { name: 'Apple Ipads', value: 'apple-ipads' },
    { name: 'Authentic Perfumes', value: 'authentic-perfumes' },
    { name: 'Clothes', value: 'clothes' },
    { name: 'DeWalt', value: 'dewalt' },
    { name: 'Electronics', value: 'electronics' },
    { name: 'Female Bag Pallets', value: 'female-bag-pallets' },
    { name: 'General Merchandise', value: 'general-merchandise' },
    { name: 'Home Depot', value: 'home-depot' },
    { name: 'Household', value: 'household' },
    { name: 'Iphones', value: 'iphones' },
    { name: 'Kitchen Appliances', value: 'kitchen-appliances' },
    { name: 'Laptop & Computer', value: 'laptop-computer' },
    { name: "Marcy's", value: 'marcys' },
    { name: 'Milwaukee', value: 'milwaukee' },
    { name: 'Mix Cosmetics and make up', value: 'mix-cosmetics-and-make-up' },
    { name: 'Mix Shoes', value: 'mix-shoes' },
    { name: 'Mix tools', value: 'mix-tools' },
    { name: 'Mystery Boxes', value: 'mystery-boxes' },
    { name: 'Ps5', value: 'ps5' },
    { name: 'Scooter', value: 'scooter' },
    { name: 'Target', value: 'target' },
    { name: 'Truckload', value: 'truckload' },
];

export const shopCategories = [
    { name: 'Authentic Perfumes', href: '/product-category/authentic-perfumes' },
    { name: 'DeWalt', href: '/product-category/dewalt' },
    { name: 'Ps5', href: '/product-category/ps5' },
    { name: 'Household', href: '/product-category/household' },
    { name: 'Truckload', href: '/product-category/truckload' },
    { name: 'Milwaukee', href: '/product-category/milwaukee' },
    { name: 'Mix Shoes', href: '/product-category/mix-shoes' },
    { name: 'Mix Cosmetics and make up', href: '/product-category/mix-cosmetics-and-make-up' },
    { name: 'General Merchandise', href: '/product-category/general-merchandise' },
    { name: 'Mix tools', href: '/product-category/mix-tools' },
    { name: 'Mystery Boxes', href: '/product-category/mystery-boxes' },
    { name: 'Home Depot', href: '/product-category/home-depot' },
    { name: 'Amazon', href: '/product-category/amazon' },
    { name: 'Clothes', href: '/product-category/clothes' },
    { name: "Marcy's", href: '/product-category/marcys' },
    { name: 'Target', href: '/product-category/target' },
    { name: 'Female Bag Pallets', href: '/product-category/female-bag-pallets' },
];

export const mainMenu = [
    { name: 'Home', href: '/' },
    { name: 'Shop', href: '/shop', hasSubmenu: true },
    { name: 'Truckload', href: '/product-category/truckload' },
    { name: 'Testimonials', href: '/testimonials' },
    { name: 'About Us', href: '/about-us' },
    { name: 'Contact Us', href: '/contact-us' },
];
